###
GET https://main-mock-server.onrender.com/destinations

###
GET https://mock-every-sunday-server.onrender.com/users

###
POST https://mock-every-sunday-server.onrender.com/users
Content-Type: application/json

{
    "name":"kaushal",
    "email":"kaushal@gmail.com",
    "password":"12345kau"
}

